import type { ProjectRecord } from './types'

type SeedProject = Omit<ProjectRecord, 'id' | 'status' | 'seoTitle' | 'seoDescription' | 'createdAt' | 'updatedAt' | 'publishedAt'>

export const DEFAULT_PROJECTS_DATA: SeedProject[] = [
  {
    slug: 'alethia',
    name: 'Aletheia',
    url: 'https://alethia.me',
    year: '2026',
    category: 'AI · Forensic Intelligence',
    accent: '#10B981',
    tagline: 'AI-Powered Anticorruption Intelligence',
    hero: 'Corruption costs the world $2.6 trillion every year. Aletheia is the platform built to fight it — with forensic rigor, court-ready evidence, and zero hallucinations.',
    summary: 'Aletheia is a multi-model AI forensic intelligence platform designed for investigative journalists, prosecutors, compliance officers, and anticorruption agencies. It ingests public records, maps hidden ownership networks, and produces courtroom-admissible reports — in a fraction of the time manual investigations require.',
    featured: true,
    sortOrder: 10,
    content: {
      role: 'Product architecture, AI orchestration, full-stack engineering, network visualization, on-premise deployment.',
      stack: ['Claude API', 'GPT-4', 'Gemini', 'Perplexity', 'Ollama', 'Node.js', 'PostgreSQL', 'D3.js', 'React + TypeScript', 'Docker / Coolify', 'Supabase'],
      stats: [
        { num: '7', label: 'phase forensic pipeline' },
        { num: '98%', label: 'investigation time saved' },
        { num: '0', label: 'hallucination tolerance' },
        { num: '2', label: 'languages (EN / SR)' },
      ],
      problem: {
        title: 'Investigations that should take weeks take years',
        body: 'Anticorruption work drowns in documents. Procurement filings, court decisions, company registries, sanctions lists, leaked databases — all scattered, inconsistent, and written for lawyers, not search engines. Under 4% of corruption cases end in successful prosecution, not because the evidence is not there, but because analysts cannot connect it fast enough.',
      },
      approach: [
        { title: 'Zero Hallucination Protocol', body: 'Every factual claim carries a mandatory inline citation an analyst can click through and verify; anything without a source is explicitly labeled and never presented as established fact.' },
        { title: 'A seven-phase forensic pipeline', body: 'Identity verification to typology scoring. Each phase produces structured output the next one consumes. The analyst stays in the loop at every handoff.' },
        { title: 'Built for sensitive infrastructure', body: 'The entire stack runs air-gapped on-premise via Ollama for clients who cannot send data to a cloud API.' },
        { title: 'Evidence that holds up in court', body: 'Reports include a full chain of custody: which model said what, which source backed the claim, which analyst approved it, and which criminal code article applies.' },
      ],
      features: [
        { title: 'Multi-model consensus engine', desc: 'Four AI providers cross-validate every finding. Conflicts flagged, never silently resolved.' },
        { title: 'Network graph visualization', desc: 'Interactive D3.js graphs expose beneficial ownership, shared directors, and shell company clusters.' },
        { title: 'Procurement anomaly detection', desc: 'Detects single-bidder tenders, value-splitting, and suspicious award patterns across public tender data.' },
        { title: 'Evidence locker', desc: 'Document upload with OCR, entity extraction, and automatic linking back to the active investigation.' },
        { title: 'Legal code mapping', desc: 'Every finding is matched to relevant criminal code articles so the prosecutorial handoff is a click.' },
        { title: 'Watchlist monitoring', desc: 'Persistent tracking of entities of interest with automated alerts for new filings, sanctions, or media mentions.' },
      ],
      outcomes: [
        { metric: '98%', label: 'reduction in investigation cycle time' },
        { metric: '5', label: 'AI providers merged in Ensemble mode' },
        { metric: '7', label: 'forensic phases automated end-to-end' },
        { metric: '100%', label: 'source citation coverage' },
      ],
      lessons: [
        'For high-stakes AI, consensus beats benchmarks.',
        'Air-gap is a feature, not a limitation.',
        'Structured handoffs between AI phases are what separates a demo from a platform.',
      ],
      quote: {
        text: 'What used to be a year of reading disclosures is now an afternoon of reviewing findings.',
        attribution: 'Pilot user — investigative team, Western Balkans',
      },
    },
  },
  {
    slug: 'woopulse',
    name: 'WooPulse',
    url: 'https://woopulse.com',
    year: '2026',
    category: 'SaaS · eCommerce AI',
    accent: '#C084FC',
    tagline: 'The AI brain for your WooCommerce store',
    hero: 'WooPulse plugs into WooCommerce and turns raw transactional data into revenue through AI-drafted recovery emails, dynamic pricing, and competitor intelligence.',
    summary: 'WooPulse is a multi-model AI platform that helps stores automate cart recovery, price optimization, product copywriting, and competitor monitoring.',
    featured: true,
    sortOrder: 20,
    content: {
      role: 'Product strategy, full-stack SaaS build, multi-model AI orchestration, WooCommerce integration, billing and onboarding.',
      stack: ['React + TypeScript', 'Vite', 'Node.js', 'WooCommerce REST API', 'Claude API', 'GPT-4o', 'Gemini', 'Ollama', 'PostgreSQL', 'Supabase', 'Stripe', 'Docker / Coolify', 'Mailgun'],
      stats: [
        { num: '€2.3M', label: 'recovered carts across platform' },
        { num: '500+', label: 'WooCommerce stores running' },
        { num: '3.5×', label: 'cart recovery lift vs baseline' },
        { num: '18%', label: 'average margin improvement' },
      ],
      problem: {
        title: 'Small stores are drowning in the work that makes them grow',
        body: 'Solo WooCommerce founders have to act as merchandisers, copywriters, pricing analysts, competitor researchers, and support reps — usually without enterprise tooling or time.',
      },
      approach: [
        { title: 'One plugin install, full intelligence layer', body: 'WooPulse connects through the WooCommerce REST API and starts scoring opportunities almost immediately.' },
        { title: 'Multi-model where it matters', body: 'Product copy and abandonment emails get consensus drafting across Claude, GPT-4o, and Gemini.' },
        { title: 'Three tiers that match how real stores grow', body: 'Starter, Growth, and Agency plans align with real operator stages.' },
        { title: 'Self-hosted Ollama for privacy-sensitive verticals', body: 'Sensitive industries can route generation through local inference rather than public APIs.' },
      ],
      features: [
        { title: 'Abandoned cart recovery', desc: 'AI drafts personalized recovery emails with product-aware incentives and timing.' },
        { title: 'Dynamic pricing optimizer', desc: 'Tracks elasticity across the catalog and proposes price points that lift margin.' },
        { title: 'AI product copywriting', desc: 'Bulk-generate product descriptions, meta titles, and short-form copy.' },
        { title: 'Competitor intelligence', desc: 'Automated monitoring of competitor prices, promotions, and launches.' },
        { title: 'Revenue command dashboard', desc: 'One screen showing revenue, AOV, recoveries, margin, and next actions.' },
        { title: 'Agency multi-store mode', desc: 'Manage multiple client stores from one login with white-label reporting.' },
      ],
      outcomes: [
        { metric: '€8.4k', label: 'recovered in the first month by a pilot store' },
        { metric: '60%', label: 'reduction in weekly operator workload' },
        { metric: '10×', label: 'faster insight-to-action loop' },
        { metric: '10,000+', label: 'products analyzed and re-written' },
      ],
      lessons: [
        'WooCommerce is an unfair distribution advantage.',
        'Founders do not want dashboards — they want verdicts.',
        'Pricing is product.',
      ],
      quote: {
        text: 'Recovered €8,400 by the end of the month from carts I thought were dead.',
        attribution: 'Pilot customer — fashion DTC, Berlin',
      },
    },
  },
  {
    slug: 'nisam-video',
    name: 'nisam.video',
    url: 'https://nisam.video',
    year: '2016 — ongoing',
    category: 'Media · AI Curation',
    accent: '#F59E0B',
    tagline: 'AI-curated video for a region the algorithm forgot',
    hero: 'A video discovery platform built for Serbian-language independent journalism, combining editorial curation with AI-assisted classification.',
    summary: 'nisam.video is a long-running, personally funded video hub that aggregates, categorizes, and surfaces independent and investigative Serbian-language content from YouTube.',
    featured: true,
    sortOrder: 30,
    content: {
      role: 'Founder, product designer, developer, curator. Solo build and continuous operation since 2016.',
      stack: ['WordPress / custom theme', 'YouTube Data API', 'PHP + MySQL', 'Custom taxonomy engine', 'JS front-end', 'AI classification layer', 'Self-hosted infrastructure'],
      stats: [
        { num: '10+', label: 'years continuous operation' },
        { num: '1000s', label: 'of videos curated' },
        { num: '2', label: 'flagship channel streams' },
        { num: '1', label: 'operator — solo project' },
      ],
      problem: {
        title: 'Algorithms do not serve small languages or small democracies',
        body: 'Serbian-speaking viewers seeking verified, independent journalism are underserved by mainstream recommendation engines built for outrage and scale.',
      },
      approach: [
        { title: 'Editorial curation as the product', body: 'Every channel admitted to the platform is vetted. Every video surfaced is categorized by a human-plus-AI pass.' },
        { title: 'A custom taxonomy engine', body: 'The platform uses a bespoke taxonomy for program, topic, subject, timeline event, and named entity.' },
        { title: 'Live streams pinned where they belong', body: 'Dedicated live-stream pages survive YouTube URL changes and channel rebrands.' },
        { title: 'Ten years of compounding archive', body: 'Every curated video and interview is still reachable at a stable URL.' },
      ],
      features: [
        { title: 'Curated channel roster', desc: 'Vetted independent and investigative sources are surfaced as first-class citizens.' },
        { title: 'Program-level categorization', desc: 'Follow programs across years, not just channel feeds.' },
        { title: 'AI classification layer', desc: 'Incoming videos are auto-tagged by topic and entity before editorial review.' },
        { title: 'Stable archive URLs', desc: 'Every video lives at a permanent nisam.video URL.' },
        { title: 'Live stream redirector', desc: 'Dedicated pages always resolve to the current live feed.' },
        { title: 'Regional-first performance', desc: 'Fast-loading design optimized for Balkan mobile networks.' },
      ],
      outcomes: [
        { metric: '10 yrs', label: 'of continuous uptime since 2016' },
        { metric: '0 €', label: 'external funding — self-sustained' },
        { metric: '100%', label: 'of featured content vetted before publication' },
        { metric: '∞', label: 'patience for stories the algorithm will not carry' },
      ],
      lessons: [
        'Scale is not the point.',
        'AI did not replace curation; it made curation tractable.',
        'Owning the URL is owning the archive.',
      ],
      quote: {
        text: 'Building nisam.video was never about product-market fit. It was about making sure the stories that matter in this region have somewhere to live.',
        attribution: 'Marko Tiosavljevic — founder, nisam.video',
      },
    },
  },
  {
    slug: 'morpheus',
    name: 'Morpheus OS',
    url: 'https://dotbooks.store',
    year: '2026',
    category: 'Open Source · Agentic Commerce',
    accent: '#06B6D4',
    tagline: 'A modular, plugin-native, AI-native ecommerce platform',
    hero: 'Catalog to checkout in a tiny core. Everything else is a plugin. Morpheus ships the agent gateway modern commerce stacks are racing toward.',
    summary: 'Morpheus OS is an open-source, event-sourced ecommerce platform with a tiny Django core, 60+ first-party plugins, and first-class agent interfaces.',
    featured: true,
    sortOrder: 40,
    content: {
      role: 'Platform architecture, core engine, plugin and theme SDK, agent kernel, MCP and UCP protocol surfaces, SEO stack, and deployment.',
      stack: ['Django 6', 'Python', 'PostgreSQL', 'Redis', 'Celery', 'NATS JetStream', 'GraphQL', 'DRF', 'three.js', 'MCP / UCP', 'OpenAI / Anthropic / Gemini / Grok / Ollama', 'Docker / Coolify'],
      stats: [
        { num: '60+', label: 'plugins enabled by default' },
        { num: '4', label: 'audience-scoped MCP endpoints' },
        { num: '20+', label: 'built-in Assistant tools' },
        { num: '~20s', label: 'one-prompt store bootstrap' },
      ],
      problem: {
        title: 'Commerce platforms bolt AI on as an afterthought',
        body: 'Most AI-for-ecommerce tooling is either a plugin that automates rules or a chatbot that advises. Neither acts as a first-class agent operating on a modular platform.',
      },
      approach: [
        { title: 'A tiny core — everything else is a plugin', body: 'The core stays deliberately small, while a modularity contract lets features mount and unmount cleanly.' },
        { title: 'AI-native, not AI-attached', body: 'A merchant assistant, agent kernel, and capability-scoped tools are designed into the platform from the start.' },
        { title: 'Agentic-commerce protocol surfaces', body: 'An MCP cluster and UCP discovery let external AI clients transact directly.' },
        { title: 'A 2026 SEO + AEO stack', body: 'Structured outputs, llms.txt, JSON-LD, feeds, and auto web stories make the catalog discoverable to search and answer engines.' },
      ],
      features: [
        { title: 'The modularity contract', desc: 'Themes own slots, plugins own features, and disabling a plugin removes its surfaces cleanly.' },
        { title: 'Hard-coded merchant Assistant', desc: 'An always-on operator in the core with 20+ tools spanning reads and gated writes.' },
        { title: 'MCP server cluster', desc: 'Audience-scoped endpoints plus UCP and Trusted-Agent discovery.' },
        { title: 'One-prompt store bootstrap', desc: 'Generate a brand voice, categories, and starter products from one sentence.' },
        { title: 'Event-sourced + transactional outbox', desc: 'Every state change emits an auditable event and outbound webhooks are signed.' },
        { title: 'Auto Google Web Stories', desc: 'A valid AMP story is generated per product from images and metadata.' },
      ],
      outcomes: [
        { metric: '60+', label: 'first-party plugins shipping by default' },
        { metric: '4', label: 'MCP surfaces + UCP discovery' },
        { metric: '15-bot', label: 'AI-crawler policy matrix' },
        { metric: 'Live', label: 'in production at dotbooks.store' },
      ],
      lessons: [
        'Modularity is only real when it is enforced.',
        'Building machine-actionable-first makes the AI layer feel native.',
        'Protocol surfaces are the moat.',
      ],
      quote: {
        text: 'Morpheus treats agents as a first-class audience that sits on top of a complete commerce platform.',
        attribution: 'Marko Tiosavljevic — creator, Morpheus OS',
      },
    },
  },
  {
    slug: 'torsor-helper',
    name: 'Torsor Helper',
    url: 'https://github.com/magnetoid/torsor-helper',
    year: '2026',
    category: 'AI · Developer Tooling',
    accent: '#7C3AED',
    tagline: 'The memory and coaching layer for AI coding agents',
    hero: 'Torsor Helper gives AI coding agents persistent memory, architectural guardrails, and a coaching layer that survives across sessions.',
    summary: 'A local-first Python MCP server that combines a project wiki, semantic memory, a symbol-level repo map, and drift guard capabilities.',
    featured: true,
    sortOrder: 50,
    content: {
      role: 'Product design, the Python MCP server, the memory, index and recall engine, the CLI, and documentation.',
      stack: ['Python 3.11+', 'Model Context Protocol', 'SQLite + FTS5', 'Vector embeddings', 'RRF hybrid fusion', 'Markdown'],
      stats: [
        { num: '4', label: 'agent failure modes addressed' },
        { num: '215', label: 'tests passing' },
        { num: '0', label: 'API keys required — local-first' },
        { num: 'v0.2', label: 'the intelligence release' },
      ],
      problem: {
        title: 'AI coding agents are brilliant in the moment and forgetful over time',
        body: 'New chats start from zero, long sessions drift, and agents quietly reintroduce patterns that were already rejected.',
      },
      approach: [
        { title: 'A pyramidal wiki the agent reads on every session start', body: 'A budgeted charter and context hierarchy situate the agent before it writes code.' },
        { title: 'External memory ranked by what is durable', body: 'Hybrid recall plus importance ordering surfaces the right memory rather than the most recent one.' },
        { title: 'Architectural intent captured as enforceable rules', body: 'ADRs-as-rules and drift checks stop rejected patterns from silently returning.' },
        { title: 'Local-first with no API key required', body: 'Markdown remains the source of truth, so memory is committable and reviewable.' },
      ],
      features: [
        { title: 'bootstrap_session', desc: 'A budgeted project summary is delivered at session start.' },
        { title: 'Hybrid recall', desc: 'Vector and FTS5 search are fused with ranking tuned for durable knowledge.' },
        { title: 'Decisions and memory', desc: 'Notes and ADRs persist as linked Markdown.' },
        { title: 'Drift guard', desc: 'Checks architecture drift against a baseline.' },
        { title: 'Repository map', desc: 'A symbol-level map feeds reuse and hotspot recommendations.' },
        { title: 'MCP-native', desc: 'Any MCP client can use it without custom integration.' },
      ],
      outcomes: [
        { metric: '215', label: 'passing tests on the engine' },
        { metric: '0', label: 'API keys needed to run the full memory layer' },
        { metric: '4-in-1', label: 'wiki + semantic memory + repo map + drift guard' },
        { metric: 'Any', label: 'MCP client — Claude Code, Codex, Cursor' },
      ],
      lessons: [
        'External memory beats a bigger context window.',
        'Markdown as the source of truth keeps memory auditable.',
        'Memory is language-agnostic; the symbol map is not.',
      ],
    },
  },
  {
    slug: 'quorum',
    name: 'Quorum',
    url: 'https://github.com/magnetoid/Quorum',
    year: '2026',
    category: 'AI · Consensus Engine',
    accent: '#F97316',
    tagline: 'One question. A council of models. A single, trusted answer.',
    hero: 'Quorum convenes a council of models, clusters their answers by meaning, measures agreement, and surfaces the most reliable response.',
    summary: 'A production-grade consensus reasoning engine designed to reduce hallucinations and vendor lock-in by orchestrating multiple models.',
    featured: true,
    sortOrder: 60,
    content: {
      role: 'Engine design, consensus and voting algorithms, semantic clustering, and tiered execution.',
      stack: ['Python 3.11+', 'OpenAI / Anthropic / Gemini / Llama / Ollama', 'High-dimensional embeddings', 'Semantic clustering', 'Speculative tiered execution', 'Apache-2.0'],
      stats: [
        { num: 'N', label: 'models in the council, not one' },
        { num: 'V2', label: 'speculative tiered execution' },
        { num: '2', label: 'domain-tuned similarity regimes' },
        { num: 'Apache-2.0', label: 'open source' },
      ],
      problem: {
        title: 'A single model is a single point of failure',
        body: 'Large language models are often confidently wrong, and betting a workflow on one provider is both fragile and misleading.',
      },
      approach: [
        { title: 'Hybrid semantic voting', body: 'Responses are clustered by meaning using embeddings rather than lexical overlap alone.' },
        { title: 'Speculative tiered execution', body: 'Cheap models answer first and expensive ones are only launched when consensus is not reached.' },
        { title: 'Domain-aware adaptive thresholds', body: 'Similarity thresholds shift depending on whether the task is code, logic, or creative text.' },
        { title: 'Make disagreement a feature', body: 'When models conflict, Quorum surfaces a disputed zone instead of silently picking a winner.' },
      ],
      features: [
        { title: 'Council orchestration', desc: 'Query multiple providers for the same question and treat their answers as votes.' },
        { title: 'Semantic clustering', desc: 'Group responses by meaning with embeddings so genuine conflicts stand out.' },
        { title: 'Disputed-zone flagging', desc: 'Dissent is shown explicitly rather than resolved behind your back.' },
        { title: 'Speculative tiers', desc: 'Heavy models are called only when needed.' },
        { title: 'Adaptive thresholds', desc: 'Per-domain similarity regimes reduce both false agreement and false disagreement.' },
        { title: 'Remote embedding fallback', desc: 'Hosted embeddings are used when local inference hardware is not available.' },
      ],
      outcomes: [
        { metric: '1', label: 'trusted answer from a whole council' },
        { metric: 'Visible', label: 'disagreement instead of hidden hallucination' },
        { metric: 'Tiered', label: 'cost — heavy models only when needed' },
        { metric: 'No', label: 'single-vendor lock-in' },
      ],
      lessons: [
        'The dangerous failure mode is confidence, not ignorance.',
        'Consensus needs to understand meaning, not match strings.',
        'Speculative tiers make multi-model affordable.',
      ],
    },
  },
  {
    slug: 'vektor',
    name: 'Vektor',
    url: 'https://github.com/magnetoid/vektor',
    year: '2026',
    category: 'AI · Autonomous Media',
    accent: '#3B82F6',
    tagline: 'Direction and magnitude in AI — an autonomous, multilingual news portal',
    hero: 'Vektor discovers AI news from hundreds of sources, synthesizes original articles, translates them, generates audio, and publishes through a full editorial CMS.',
    summary: 'An autonomous, multilingual AI news portal with a seven-stage discovery-to-publish pipeline and a human editor in the loop.',
    featured: true,
    sortOrder: 70,
    content: {
      role: 'Architecture, the discovery-to-publish pipeline, AI orchestration, the editorial CMS, internationalization, and deployment.',
      stack: ['Next.js 16', 'TypeScript', 'Tailwind', 'shadcn/ui', 'Payload CMS', 'Drizzle ORM + Postgres', 'Redis', 'BullMQ', 'Claude', 'ElevenLabs', 'Cloudflare R2', 'Plausible / Sentry'],
      stats: [
        { num: '7', label: 'stage discover-to-publish pipeline' },
        { num: '2', label: 'launch languages (EN / SR)' },
        { num: 'pgvector', label: 'cosine dedup of sources' },
        { num: 'Graceful', label: 'stub fallback per stage' },
      ],
      problem: {
        title: 'AI news is a firehose — and it ignores small languages',
        body: 'The volume of AI news is impossible to follow, overwhelmingly English-first, and badly served for smaller audiences who need synthesis and translation.',
      },
      approach: [
        { title: 'A seven-stage pipeline, gated and resilient', body: 'discover → dedup → rewrite → verify → translate → tts → publish, with stubs for development and resilience.' },
        { title: 'Deduplicate before you spend a token', body: 'Sources are hashed and embedded before rewrite work begins.' },
        { title: 'Synthesize, then verify', body: 'Claude rewrites sources into original articles and a verify stage acts as a hallucination guard.' },
        { title: 'Multilingual and multimodal by default', body: 'Every article can ship in multiple languages and audio formats through the editorial CMS.' },
      ],
      features: [
        { title: 'Source discovery', desc: 'RSS-driven ingestion from hundreds of sources into a raw queue.' },
        { title: 'Semantic dedup', desc: 'Hash + embedding + pgvector similarity collapses near-duplicate stories.' },
        { title: 'Claude rewrite', desc: 'Original article synthesis rather than thin summarization.' },
        { title: 'Hallucination verify', desc: 'A dedicated verification stage guards accuracy before translation or publish.' },
        { title: 'EN → SR translation + audio', desc: 'Serbian translation plus multilingual narration stored on R2.' },
        { title: 'Editorial CMS', desc: 'Payload CMS gives editors full oversight of the autonomous pipeline.' },
      ],
      outcomes: [
        { metric: '7', label: 'pipeline stages wired end-to-end' },
        { metric: '2', label: 'languages shipped per article' },
        { metric: 'Text + audio', label: 'every story, automatically' },
        { metric: 'Editor', label: 'always in the loop via Payload' },
      ],
      lessons: [
        'Gate every AI stage and give it a stub.',
        'Dedup before you generate.',
        'Autonomy still needs an editor.',
      ],
    },
  },
  {
    slug: 'imba-crm',
    name: 'Imba CRM',
    url: 'https://github.com/magnetoid/imba-crm',
    year: '2026',
    category: 'AI · CRM Platform',
    accent: '#EAB308',
    tagline: 'AI-assisted CRM with a multi-provider model router',
    hero: 'A lead funnel, inbox, AI email generation with manual approval, proposals, and invoices — wired to a model router that fans every request across six AI providers with policy-based fallbacks and cost accounting.',
    summary: 'Imba CRM is an AI-assisted CRM built as a pnpm monorepo: an admin-first Vite + React SPA and a model-router library and HTTP server that routes requests across Anthropic, OpenAI, Google, Ollama, Deepgram, and Perplexity with policy-based fallbacks and cost accounting.',
    featured: true,
    sortOrder: 80,
    content: {
      role: 'Architecture, the model-router, the admin SPA, Supabase integration, and the proposals, invoices, and onboarding flows.',
      stack: ['Vite + React + TypeScript', 'TailwindCSS + Radix', 'Supabase (Edge Functions, Postgres)', 'model-router (TypeScript)', 'Anthropic / OpenAI / Google', 'Perplexity / Deepgram / Ollama', 'Docker'],
      stats: [
        { num: '6', label: 'AI providers behind one router' },
        { num: '2', label: 'deployment stacks (edge fn / HTTP)' },
        { num: 'Per-call', label: 'cost accounting' },
        { num: 'Manual', label: 'approval on every AI email' },
      ],
      problem: {
        title: 'Every project re-implements the same CRM and AI plumbing',
        body: 'A lead funnel, an inbox, AI-drafted outreach, proposals, invoices — every product needs them and every product rebuilds them. Wiring AI in directly also creates vendor lock-in, brittle outages, and invisible spend.',
      },
      approach: [
        { title: 'One model router, six providers', body: 'A single router fans requests across Anthropic, OpenAI, Google, Ollama, Deepgram, and Perplexity with policy-based fallbacks and cost accounting.' },
        { title: 'A human gate on anything that leaves the building', body: 'AI drafts outreach email, but nothing sends without manual approval.' },
        { title: 'Two deployment stacks for one frontend', body: 'The same admin SPA can run against Supabase Edge Functions or a self-hosted model-router HTTP server.' },
        { title: 'Designed to be a shared backend', body: 'Leads, inbox, proposals, invoices, and the router are built as a reusable backend across products.' },
      ],
      features: [
        { title: 'Lead funnel', desc: 'A pipeline view of leads from first touch through qualification to close.' },
        { title: 'Inbox', desc: 'A unified place to work conversations, with AI assistance on tap.' },
        { title: 'AI email generation', desc: 'Drafts outreach and replies, gated behind explicit manual approval before anything sends.' },
        { title: 'Proposals & invoices', desc: 'Turn a qualified lead into a sent proposal and a tracked invoice without leaving the CRM.' },
        { title: 'Multi-provider model router', desc: 'Anthropic, OpenAI, Google, Ollama, Deepgram, and Perplexity behind one interface with fallbacks.' },
        { title: 'Cost accounting', desc: 'Every AI call is metered at the router, so spend is visible per request rather than discovered on the invoice.' },
      ],
      outcomes: [
        { metric: '6', label: 'providers swappable without touching the app' },
        { metric: '1', label: 'router to integrate instead of N SDKs' },
        { metric: 'Tracked', label: 'AI cost on every request' },
        { metric: 'Reusable', label: 'CRM backend across projects' },
      ],
      lessons: [
        'Route AI through one seam, not many.',
        'Keep a human on the send button.',
        'Build the CRM as a backend, not a feature.',
      ],
    },
  },
  {
    slug: 'influencer-hub',
    name: 'Influencer Hub',
    url: 'https://influencer-hub.info',
    year: '2026',
    category: 'Development · Marketplace',
    accent: '#EC4899',
    tagline: 'A two-sided creator marketplace with escrow and built-in content rights',
    hero: 'Where vetted creators sell services and brands hire them — escrow payments, content rights baked into every deal, and a production-grade Next.js 16 and Stripe Connect stack underneath.',
    summary: 'Influencer Hub is a two-sided creator marketplace where creators list services and brands hire them, built on Next.js 16, React 19, Prisma, PostgreSQL, Auth.js v5, and Stripe Connect.',
    featured: true,
    sortOrder: 90,
    content: {
      role: 'Full-stack build, the marketplace and payments architecture, authentication, and Docker deployment.',
      stack: ['Next.js 16 (App Router, Turbopack)', 'React 19', 'TypeScript', 'Tailwind CSS 4', 'Auth.js v5', 'Prisma 6', 'PostgreSQL 16', 'Stripe Connect', 'Resend', 'Docker'],
      stats: [
        { num: '2-sided', label: 'creators and brands' },
        { num: 'Escrow', label: 'payments via Stripe Connect' },
        { num: 'Built-in', label: 'content rights per deal' },
        { num: '1 cmd', label: 'Docker stack — migrate + seed on boot' },
      ],
      problem: {
        title: 'Creator deals run on trust and handshakes',
        body: 'Brand-creator collaborations are mostly informal: payment happens on faith, content rights are vague, and neither side has a neutral layer holding the deal together.',
      },
      approach: [
        { title: 'Escrow as the default, not an add-on', body: 'Payments flow through Stripe Connect with the marketplace holding funds until work is delivered.' },
        { title: 'Content rights written into the deal', body: 'Usage rights are part of the transaction itself rather than a side agreement.' },
        { title: 'Vetted supply', body: 'Creators are vetted before they can sell, keeping quality high and the roster curated.' },
        { title: 'Production-grade from day one', body: 'Next.js 16, Prisma migrations and seeds on container start, Auth.js v5, and a one-command Docker stack mirror production.' },
      ],
      features: [
        { title: 'Creator profiles & services', desc: 'Creators list the services they sell with the terms attached.' },
        { title: 'Brand hiring flow', desc: 'Brands discover vetted creators and book them through a structured deal.' },
        { title: 'Escrow payments', desc: 'Stripe Connect holds funds until delivery and handles marketplace payouts.' },
        { title: 'Content-rights terms', desc: 'Usage rights are baked into each deal rather than negotiated on the side.' },
        { title: 'Auth.js v5', desc: 'Credentials sign-in plus optional Google OAuth, with magic-link email via Resend.' },
        { title: 'One-command stack', desc: 'docker compose up brings up the app and Postgres, running migrations and seeding demo creators automatically.' },
      ],
      outcomes: [
        { metric: 'Both', label: 'sides protected by escrow' },
        { metric: 'Clear', label: 'content rights on every deal' },
        { metric: 'Vetted', label: 'creator roster, not an open free-for-all' },
        { metric: 'Reproducible', label: 'production-parity Docker deploy' },
      ],
      lessons: [
        'The marketplace earns its cut by removing risk.',
        'Bake the contract into the transaction.',
        'Make the dev stack mirror production.',
      ],
    },
  },
  {
    slug: 'wp-interlinking',
    name: 'WP Interlinking',
    url: 'https://github.com/magnetoid/wp-interlinking',
    year: '2026',
    category: 'Marketing · SEO Automation',
    accent: '#0EA5E9',
    tagline: 'AI-powered SEO internal linking for WordPress',
    hero: 'Internal links are one of the most powerful and most neglected SEO levers. WP Interlinking automates the entire process: TF-IDF keyword-to-URL mapping, site-health scoring, and six AI providers, with zero manual work.',
    summary: 'WP Interlinking is a WordPress plugin that automates internal linking with TF-IDF relevance analysis, site-health scoring, and six AI providers suggesting and placing links.',
    featured: true,
    sortOrder: 100,
    content: {
      role: 'Plugin architecture, the TF-IDF relevance engine, AI-provider integration, and the WordPress admin experience.',
      stack: ['PHP 7.2+', 'WordPress 5.8+', 'TF-IDF analysis', '6 AI providers', 'GPL-2.0'],
      stats: [
        { num: '6', label: 'AI providers supported' },
        { num: 'v5.0.0', label: 'mature release line' },
        { num: 'TF-IDF', label: 'relevance scoring' },
        { num: 'Site', label: 'health scoring built in' },
      ],
      problem: {
        title: 'The best SEO lever nobody pulls',
        body: 'Internal linking helps search engines understand structure and distribute authority, yet it is almost always neglected because doing it well by hand is tedious and never-ending.',
      },
      approach: [
        { title: 'TF-IDF, not guesswork', body: 'The plugin scores how relevant a target URL actually is for a given phrase instead of naive keyword matching.' },
        { title: 'Six AI providers behind the suggestions', body: 'Suggestions and refinement come from multiple providers rather than a single vendor.' },
        { title: 'Site-health scoring', body: 'A health score turns internal-linking structure into an observable number.' },
        { title: 'Zero manual work', body: 'Keyword-to-URL mapping, scoring, and placement are automated inside a native WordPress admin.' },
      ],
      features: [
        { title: 'Keyword → URL mapping', desc: 'Maps the phrases that matter to the pages that should rank for them.' },
        { title: 'TF-IDF analysis', desc: 'Scores relevance properly instead of matching strings, so links land where they help.' },
        { title: 'Site health score', desc: 'Quantifies the internal-linking health of the whole site at a glance.' },
        { title: 'Six AI providers', desc: 'Provider-agnostic suggestions rather than lock-in to one model.' },
        { title: 'Automated placement', desc: 'Builds the internal-link structure with no manual editing pass.' },
        { title: 'WordPress-native admin', desc: 'Lives where the content already does — inside the WordPress dashboard.' },
      ],
      outcomes: [
        { metric: '6', label: 'AI providers, no single-vendor bet' },
        { metric: 'Automated', label: 'internal linking end-to-end' },
        { metric: 'Scored', label: 'site health, not a black box' },
        { metric: 'Zero', label: 'manual linking work' },
      ],
      lessons: [
        'Automate the high-value chore.',
        'Relevance has to be measured, not guessed.',
        'Stay provider-agnostic.',
      ],
    },
  },
  {
    slug: 'seo-skills-for-ai-agents',
    name: 'SEO Skills for AI Agents',
    url: 'https://github.com/magnetoid/seo-skills-for-ai-agents',
    year: '2026',
    category: 'Marketing · AI SEO',
    accent: '#22C55E',
    tagline: 'Expert-level technical SEO knowledge for AI coding assistants',
    hero: 'Stop fighting your AI when it writes bad, un-crawlable HTML. A pack of 14 skills that forces any AI coding assistant to act as an expert technical SEO — every time.',
    summary: 'SEO Skills for AI Agents is an open-source skill pack that gives coding assistants expert technical-SEO knowledge: semantic HTML, Core Web Vitals, structured data, E-E-A-T, JavaScript SEO, ecommerce, international, and AI search.',
    featured: true,
    sortOrder: 110,
    content: {
      role: 'SEO research, skill authoring, and multi-IDE packaging.',
      stack: ['Markdown skills', 'Cursor / Claude / Copilot rules', 'Google Search Central aligned', 'MIT'],
      stats: [
        { num: '14', label: 'expert SEO skills' },
        { num: 'Google', label: 'Search Central aligned' },
        { num: 'Multi-IDE', label: 'Cursor / Claude / Copilot / …' },
        { num: 'MIT', label: 'open source' },
      ],
      problem: {
        title: 'AI assistants write code that search engines cannot read',
        body: 'Coding assistants happily ship div soup, skip semantic structure, ignore Core Web Vitals, and forget structured data entirely, leaving developers to fight their own tools.',
      },
      approach: [
        { title: 'Codify expert SEO as agent skills', body: 'Knowledge is written as explicit skills the assistant must follow rather than a vague prompt.' },
        { title: 'Aligned to Google Search Central', body: 'The guidance follows Google’s published source of truth rather than folklore.' },
        { title: 'Cover the full 2026 surface', body: 'Semantic HTML, CWV, structured data, E-E-A-T, JavaScript SEO, ecommerce, international, and AI search are covered.' },
        { title: 'Install anywhere an agent runs', body: 'Clone into a project, add as a submodule, or pull with a one-liner across common AI tooling.' },
      ],
      features: [
        { title: 'Semantic HTML', desc: 'Forces correct, accessible, crawlable markup instead of div soup.' },
        { title: 'Core Web Vitals', desc: 'Bakes performance budgets and CWV awareness into generated code.' },
        { title: 'Structured data', desc: 'Proper JSON-LD so pages are eligible for rich results and AI citation.' },
        { title: 'E-E-A-T & JS SEO', desc: 'Guidance on trust signals and rendering so JavaScript apps stay indexable.' },
        { title: 'Ecommerce & international', desc: 'Catalog, hreflang, and multi-market patterns done correctly.' },
        { title: 'Multi-IDE install', desc: 'Clone, submodule, or one-liner — wired for Cursor, Claude, Copilot, and more.' },
      ],
      outcomes: [
        { metric: '14', label: 'skills enforcing expert SEO' },
        { metric: 'By default', label: 'crawlable, rankable output' },
        { metric: 'Any', label: 'AI assistant or IDE' },
        { metric: 'Aligned', label: 'to Google Search Central' },
      ],
      lessons: [
        'Encode the standard so the model cannot drift from it.',
        'Anchor to the source of truth.',
        'SEO in 2026 includes AI answer engines.',
      ],
    },
  },
]
